# Generated by Django 5.0.7 on 2024-09-30 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npi', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('specialty', models.CharField(default='General', max_length=255)),
                ('office_address', models.TextField(default='Unknown')),
                ('working_schedule', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic', models.ManyToManyField(to='dental.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ssn_last_4', models.CharField(blank=True, max_length=4, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('doctor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dental.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('procedure', models.CharField(choices=[('Cleaning', 'Cleaning'), ('Filling', 'Filling'), ('Root Canal', 'Root Canal'), ('Crown', 'Crown'), ('Teeth Whitening', 'Teeth Whitening')], max_length=255)),
                ('date_booked', models.DateField(auto_now_add=True)),
                ('time_slot', models.PositiveIntegerField(blank=True, default=None)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('procedures_done', models.CharField(default='General', max_length=255)),
                ('doctors_notes', models.TextField(default='No notes provided')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.patient')),
            ],
        ),
    ]
